/* ═══════════════════════════════════════════════════════════════
   DATOS PRESUPUESTARIOS — Municipio de Tres de Febrero
   Fuentes: RAFAM oficial 2024 (firmado 28/02/2025)
            RAFAM oficial 2025 (firmado 20/02/2026 + Recursos firmado 03/02/2026)
            RAFAM provisional 2026 (al 31/03/2026, anualizados ×4)
   ─────────────────────────────────────────────────────────────
   Para actualizar un año: editar el bloque correspondiente en DATA.
   Para GitHub Pages: subir index.html + datos.js + render.js en la misma carpeta.
═══════════════════════════════════════════════════════════════ */

const DATA = {

  /* ─────────────── 2024 ─────────────── */
  2024: {
    status: 'confirmed',
    fuente: 'RAFAM · Rendición de Cuentas firmada 28/02/2025',
    ipc: 1.178,  // inflación 2024 = 117,8%

    resumen: {
      ejecutado:     91335.66,
      percibido:     99810.92,
      presupAprobado:56761.80,
      superavitArt43:10203.77,
      resultadoArt44:10864.53,
      saldoCajaFin:  18058.37,
      saldoCajaIni:  3066.45,
      deudaFlotante: 5563.84,
      ingCorrientes: 99276.06,
      gasCorrientes: 85048.37,
      ahorroCorriente:14228.68,
      recursosCapital:274.83,
      gastosCapital:  4266.30,
      paritaria: 1.39,  // 139% acumulado
    },

    recursos: {
      totalDevengado: 109748.60,
      totalPercibido: 99810.92,
      origenMunicipal: 58614.64,  // percibido
      origenProvincial:41149.36,
      origenNacional:  46.92,
      tipos: [
        { label: 'Tasas municipales',              val: 41222.23 },
        { label: 'Coparticipación + otros trib.',  val: 35636.31 },
        { label: 'Transferencias corrientes prov.',val: 11038.21 },
        { label: 'Rentas propiedad (intereses)',   val:  3425.45 },
        { label: 'Multas y derechos',              val:  2213.99 },
        { label: 'Venta bienes y servicios',       val:    69.07 },
        { label: 'Recursos propios de capital',    val:   266.87 },
      ],
      tasas: [
        { label: 'Insp. Seg. e Higiene (TISH)',    val: 22146.42 },
        { label: 'Servicios Generales',            val: 16444.77 },
        { label: 'Tasa de Seguridad',              val:  3516.16 },
        { label: 'Salud Emergencias + At. Primaria',val: 2259.86 },
        { label: 'Mantenimiento Ctros Deportivos', val:  1627.81 },
        { label: 'Patente Automotores',            val:  1401.39 },
        { label: 'Estacionamiento Medido',         val:   834.59 },
      ],
      tributarios: [
        { label: 'Coparticipación Pcial. Ley 10.559', val: 26245.54, orig: 'Provincial' },
        { label: 'Canon EDENOR',                      val:  3564.84, orig: 'Municipal' },
        { label: 'Fondo Mpal. Inclusión Social L.13863',val:1804.79, orig: 'Provincial' },
        { label: 'Fondo Fort. Fiscal Mpal. Ley 15.480',val:1338.95,  orig: 'Municipal' },
        { label: 'Fondo Fort. Recursos Municipales',   val: 1400.82, orig: 'Provincial' },
        { label: 'Descentralización Ing. Brutos',      val:  387.21, orig: 'Provincial' },
        { label: 'CEAMSE - Recepción Residuos',        val:  504.39, orig: 'Municipal' },
        { label: 'Participación Casinos + Bingo + Hip.',val:  272.78, orig: 'Provincial' },
      ],
      fondos: [
        { label: 'Desarrollo Urbano y Hábitat (Mpal.)',  si:73.10,  ing:1061.68, eg:1020.76, sc:114.01 },
        { label: 'Estacionamiento Medido (Mpal.)',        si:12.96,  ing:834.59,  eg:271.59,  sc:575.96 },
        { label: 'Derechos Construcción Ord. 3440 (Mpal.)',si:43.38,ing:550.92,  eg:328.45,  sc:265.85 },
        { label: 'Fondo Educativo Ley 26.075 (Prov.)',   si:67.22,  ing:2717.48, eg:1594.98, sc:1189.72},
        { label: 'SAE Serv. Alimentario Escolar (Prov.)',si:13.97,  ing:3118.01, eg:3027.03, sc:104.95 },
        { label: 'MESA Bonaerense (Prov.)',               si:27.28,  ing:3613.45, eg:3598.38, sc:42.34  },
        { label: 'Fdo. Fort. Programas Sociales (Prov.)',si:66.05,  ing:561.31,  eg:568.06,  sc:59.29  },
        { label: 'Fondos Nacionales (Red Cloacal LH OC70291)',si:0, ing:122.58,  eg:0,       sc:122.58 },
      ],
    },

    gastos: {
      total:           91335.66,
      pagado:          85771.82,
      deudaFlotante:   5563.84,
      alertaPrincipal: 'El <strong>49% del gasto</strong> son Servicios No Personales, dominados por <strong>Higiene Urbana ($26.702 M)</strong> — el ítem de mayor sensibilidad para negociar el presupuesto 2027.',
      porObjeto: [
        { label: 'Gastos en personal',      val: 26421.87, pct: 28.9, impago: 0,       color: 'rgba(13,148,136,.65)'  },
        { label: 'Servicios no personales', val: 44564.62, pct: 48.8, impago: 4072.44, color: 'rgba(220,38,38,.65)'   },
        { label: 'Transferencias',          val: 11192.41, pct: 12.3, impago: 796.64,  color: 'rgba(37,99,235,.65)'   },
        { label: 'Bienes de uso',           val:  4266.30, pct:  4.7, impago: 314.97,  color: 'rgba(234,88,12,.65)'   },
        { label: 'Bienes de consumo',       val:  2891.79, pct:  3.2, impago: 379.79,  color: 'rgba(217,119,6,.65)'   },
        { label: 'Servicio de la deuda',    val:  1666.68, pct:  1.8, impago: 0,       color: 'rgba(100,116,139,.65)' },
        { label: 'Activos financieros',     val:   331.99, pct:  0.4, impago: 0,       color: 'rgba(124,58,237,.65)'  },
      ],
      programas: [
        { label: 'Higiene Urbana y Control Microbasurales', val: 26701.70 },
        { label: 'Act. Centrales (personal + gastos gles.)',val: 26445.54 },
        { label: 'SAE + MESA Bonaerense',                   val:  7675.93 },
        { label: 'Atención Primaria de la Salud',           val:  1832.94 },
        { label: 'Bacheo y Repavimentación',                val:  1433.48 },
        { label: 'Obras Viales',                            val:   864.50 },
        { label: 'Fortalecimiento Infraestructura Educativa',val:  726.53 },
        { label: 'Arbolado Público + Espacios Públicos',    val:   694.71 },
      ],
    },

    secretarias: [
      // Datos reales RAFAM 2024 — Situación Económico-Financiera (por programa)
      { label: 'Ambiente y Servicios Públicos', val: 30692.31, nota: 'Higiene Urbana + arbolado + alumbrado',
        programas: [
          { label: 'Higiene Urbana y Control Microbasurales', val: 26701.70 },
          { label: 'Mantenimiento Arbolado Público',          val:   694.71 },
          { label: 'Mantenimiento Sistema Alumbrado',         val:   743.56 },
          { label: 'Mantenimiento Infraestructura Urbana',    val:   155.62 },
          { label: 'Mantenimiento Sistema Pluvial',           val:   103.84 },
          { label: 'Centro Educativo Ambiental',              val:    36.82 },
          { label: 'Cementerio + Espacios Públicos',          val:    56.06 },
        ]
      },
      { label: 'Educación y Cultura',           val: 12365.01, nota: 'SAE + MESA Bonaerense + infraestructura',
        programas: [
          { label: 'SAE + MESA Bonaerense',                        val:  7675.93 },
          { label: 'Fortalecimiento Infraestructura Educativa',     val:   726.53 },
          { label: 'Primera Infancia y Jardines Municipales',       val:   993.30 },
          { label: 'Promoción Cultural y Patrimonial',              val:   683.83 },
          { label: 'Fortalecimiento Escuelas Municipales',          val:    77.33 },
        ]
      },
      { label: 'Secretaría de Salud',           val:  7313.87, nota: 'Atención primaria, SAME, hospitales',
        programas: [
          { label: 'Atención Primaria de la Salud',     val: 1832.94 },
          { label: 'Atención Médica Emergencias (SAME)',val:  768.49 },
          { label: 'Hospital Oftalmológico',            val:  381.36 },
          { label: 'Hospital Odontológico',             val:  409.40 },
          { label: 'Epidemiología + Vectores',          val:  152.36 },
          { label: 'Programas Sanitarios',              val:   99.57 },
          { label: 'Antropozoonosis',                   val:   72.96 },
          { label: 'Red Pública Salud AMBA',            val:  198.25 },
          { label: 'Plan SUMAR + Proteger',             val:   22.09 },
        ]
      },
      { label: 'Obras Públicas',                val:  5567.87, nota: 'Vialidad + infraestructura + servicios',
        programas: [
          { label: 'Bacheo y Repavimentación',         val: 1433.48 },
          { label: 'Obras Viales',                     val:  864.50 },
          { label: 'Obras de Infraestructura',         val:  367.58 },
          { label: 'Servicios Generales (Obras)',       val: 1075.26 },
          { label: 'Puesta en Valor Espacios Verdes',  val:    9.87 },
          { label: 'Centros Comerciales + Accesibilidad',val:  81.54 },
          { label: 'FIM - Fondo Infraest. Municipal',  val:  128.52 },
          { label: 'Casa Propia - Construir Futuro',   val:    3.89 },
        ]
      },
      { label: 'Finanzas y Eficiencia del Estado', val: 6633.16, nota: 'Hacienda + informática + servicios adm.',
        programas: [
          { label: 'Coordinación y Adm. de Ingresos',   val:  994.94 },
          { label: 'Coordinación y Adm. de Gastos',     val:  303.89 },
          { label: 'Coordinación Servicios Informáticos',val:  811.42 },
        ]
      },
      { label: 'Secretaría de Seguridad',       val:  5941.23, nota: 'Video vigilancia + protección ciudadana + defensa civil',
        programas: [
          { label: 'Fortalecimiento Sistema Video Vigilancia', val:  742.85 },
          { label: 'Fortalecimiento Protección Ciudadana',     val:  523.96 },
          { label: 'Defensa Civil',                            val:  568.11 },
          { label: 'Centro Atención Víctimas',                 val:  493.50 },
          { label: 'Coordinación Sistema Seguridad Local',     val:  118.98 },
        ]
      },
      { label: 'Secretaría General',            val:  1613.85, nota: 'Prensa + comunicación + coordinación',
        programas: [
          { label: 'Prensa y Comunicación',          val:  325.83 },
          { label: 'Comunicación y Contenido',       val:  668.39 },
          { label: 'Coordinación General Gestión',   val:  122.10 },
          { label: 'Legal y Técnica',                val:  164.45 },
          { label: 'Coordinación Adm. de Gastos',    val:  501.69 },
        ]
      },
      { label: 'Desarrollo Humano y Hábitat',   val:  4980.49, nota: 'Social + alimentaria + hábitat',
        programas: [
          { label: 'Emergencia Social y Seg. Alimentaria', val: 2437.33 },
          { label: 'Protección y Restitución Derechos NNA',val:  180.40 },
          { label: 'Espacios Comunitarios Territoriales',  val:   98.95 },
          { label: 'Economía Social y Popular',            val:  129.00 },
          { label: 'Programa Hábitat Sustentable',         val:  182.95 },
          { label: 'Géneros y Derechos Humanos',           val:   38.94 },
          { label: 'Inclusión Personas con Discapacidad',  val:  110.46 },
        ]
      },
      { label: 'Secretaría de Deporte',         val:  2056.36, nota: 'Absorbida por Capital Humano en 2025', eliminada25: true,
        programas: [
          { label: 'Deporte Inclusivo',               val:   81.20 },
          { label: 'Apoyo Deportistas y Clubes',      val:  511.99 },
          { label: 'Deporte Educativo',               val:   77.25 },
          { label: 'Ligas Deportivas + Bonaerenses',  val:  358.94 },
          { label: 'Fort. Infraestructura Centros Dep.',val:  88.63 },
        ]
      },
      { label: 'Jefatura de Gabinete',          val:  2409.40, nota: 'Dividida en 2025 (Coordinación + otras)', eliminada25: true,
        programas: [
          { label: 'Asuntos Institucionales', val:  105.43 },
          { label: 'Juventud',               val:  254.96 },
          { label: 'Recursos Humanos',        val:  469.91 },
        ]
      },
      { label: 'Des. Territorial y Movilidad',  val:  2236.42, nota: 'Funciones parcialmente reasignadas en 2025',
        programas: [
          { label: 'Plan Integral Movilidad',           val:   28.93 },
          { label: 'Regularización Dominial Altos Podestá',val: 94.79 },
          { label: 'Fortalecimiento Seguridad Vial',    val:   40.48 },
          { label: 'Sistema Ord. Centralidades y Estac.',val:  69.68 },
          { label: 'Plan Urbano Estratégico',           val:  171.86 },
          { label: 'Desarrollo Urbano y Hábitat Sust.', val:   12.00 },
        ]
      },
      { label: 'Control Municipal',             val:  1797.48, nota: 'Funciones fusionadas en 2025',
        programas: [
          { label: 'Plan Anual Seguridad e Higiene',       val:  857.09 },
          { label: 'Ordenamiento Espacio Público',         val:  286.83 },
          { label: 'Gestión Integral Habilitaciones',      val:  198.44 },
        ]
      },
      { label: 'Licencias de Conducir / Atención al Vecino', val: 1014.36, nota: 'Fusionada/reasignada en 2025',
        programas: [
          { label: 'Licencias de Conducir',    val:  115.18 },
          { label: 'Gobierno Cercano y Accesible',val: 153.51 },
          { label: 'Defensa al Consumidor',    val:   25.36 },
        ]
      },
      { label: 'Trabajo y Producción',          val:   753.99, nota: '+464% nominal en 2025',
        programas: [
          { label: 'Formación para el Trabajo',     val:  54.88 },
          { label: 'Dist. Innovación y Conocimiento',val: 34.39 },
          { label: 'Parque Industrial y PYMES',     val:   3.81 },
          { label: 'Microcréditos 3FEmprende',      val:  10.13 },
        ]
      },
      { label: 'Juzgado de Faltas',             val:   156.16, nota: '',
        programas: [
          { label: 'Oficina de Faltas', val: 21.19 },
        ]
      },
      { label: 'H.C.D.',                        val:  1794.60, nota: '',
        programas: [
          { label: 'Actividades Centrales HCD', val: 1794.60 },
        ]
      },
    ],

    personal: {
      total: 2726,
      permanente: 1161,
      mensualizado: 1565,
      gastoTotal: 26421.87,
      paritaria: 139,
      porSecretaria: [
        { label: 'Salud',                     val: 537 },
        { label: 'Seguridad',                 val: 430 },
        { label: 'Educación y Cultura',       val: 335 },
        { label: 'Ambiente y Serv. Públicos', val: 196 },
        { label: 'Control Municipal',         val: 169 },
        { label: 'Obras Públicas',            val: 139 },
        { label: 'Gobierno',                  val: 124 },
        { label: 'HCD',                       val: 101 },
        { label: 'Des. Humano y Hábitat',     val: 106 },
        { label: 'Hacienda',                  val:  88 },
        { label: 'Atención al Vecino',        val:  88 },
        { label: 'Estratégicos + General',    val: 128 },
        { label: 'Des. Territorial Movilidad',val: 121 },
        { label: 'Juzgado + Faltas',          val:  22 },
        { label: 'Deporte',                   val: 109 },
        { label: 'Trabajo y Producción',      val:  33 },
        { label: 'Secretaría de Gobierno',    val: 124 },
      ],
      componentes: [
        { label: 'Retribuciones (perm. + temp.)', val: 12466.16 },
        { label: 'Horas extras',                  val:  2016.26 },
        { label: 'Contribuciones patronales',     val:  3229.36 },
        { label: 'SAC',                           val:  1664.04 },
        { label: 'Otras bonificaciones',          val:  2898.90 },
        { label: 'Bonif. extraordinaria',         val:   794.95 },
        { label: 'DIPREGEP + Asig. familiares',   val:   813.08 },
        { label: 'Asist. social + complementos',  val:    19.57 },
      ],
    },
  },

  /* ─────────────── 2025 ─────────────── */
  2025: {
    status: 'confirmed',
    fuente: 'RAFAM · Rendición de Cuentas firmada 2026 · Datos RAFAM oficiales',
    ipc: 0.315,  // IPC 2025: 31,5% (INDEC)

    resumen: {
      ejecutado:      150745.28,
      percibido:      160362.00,  // estimado: ejecutado + superávit Art43
      presupAprobado: 121901.00,
      superavitArt43:   9617.00,
      resultadoArt44:  10100.00,  // estimado (Art44 = Art43 + saldo anterior − deuda)
      saldoCajaFin:   30734.00,
      saldoCajaIni:   18058.37,
      deudaFlotante:   8431.00,
      ingCorrientes: 153578.00,
      gasCorrientes: 129215.00,
      ahorroCorriente: 24363.00,
      recursosCapital: 1200.00,   // estimado
      gastosCapital:  15397.00,
      paritaria: 0.25,  // 25% acumulado 2025
    },

    recursos: {
      // Fuente: RAFAM · Estado de Ejecución de Recursos 2025 · firmado 03/02/2026
      // Todos los valores = PERCIBIDO (efectivamente ingresado a caja)
      totalDevengado: 173134.94,
      totalPercibido: 154471.82,
      origenMunicipal:  89596.78,   // tasas + derechos + multas + otros + rentas + venta + capital mpal.
      origenProvincial: 18794.67,   // transferencias corrientes provinciales
      origenNacional:     305.04,   // transferencias nacionales
      tipos: [
        { label: 'Tasas municipales',               val: 66748.23 },
        { label: 'Coparticipación + otros trib.',    val: 49020.79 },
        { label: 'Transferencias corrientes',        val: 19099.71 },
        { label: 'Rentas propiedad (intereses dep.)',val:  7718.77 },
        { label: 'Derechos municipales',             val:  3587.01 },
        { label: 'Multas',                           val:  2903.02 },
        { label: 'Otros no tributarios',             val:  4366.24 },
        { label: 'Venta bienes y servicios',         val:   134.16 },
        { label: 'Recursos propios de capital',      val:   646.95 },
      ],
      tasas: [
        { label: 'Insp. Seg. e Higiene (TISH)',      val: 35112.58 },
        { label: 'Servicios Generales',              val: 30916.72 },
        { label: 'Derechos de Construcción',         val:  2081.05 },
        { label: 'Patentes (autom. + rodados)',       val:  2173.37 },
        { label: 'Estacionamiento Medido',           val:  1159.20 },
        { label: 'Tasa de Seguridad',                val:   168.26 },
        { label: 'Salud y emergencias',              val:   184.30 },
        { label: 'Multas y contravenciones',         val:  2903.02 },
      ],
      tributarios: [
        { label: 'Coparticipación Pcial. Ley 10.559', val: 36249.49, orig: 'Provincial' },
        { label: 'Canon EDENOR',                      val:  6819.43, orig: 'Municipal' },
        { label: 'Fondo Mpal. Inclusión Social L.13863',val:2670.74, orig: 'Provincial' },
        { label: 'Fondo Fort. Recursos Municipales',   val: 2048.97, orig: 'Provincial' },
        { label: 'Descentralización Ing. Brutos',      val:   580.20, orig: 'Provincial' },
        { label: 'Apuestas + Bingo + Casinos + Máq.',  val:   524.76, orig: 'Provincial' },
        { label: 'Juegos On Line',                     val:    47.73, orig: 'Municipal' },
      ],
      fondos: [
        { label: 'SAE - Serv. Alimentario Escolar (Prov.)',  si:   0, ing: 4010.37, eg: 4010.37, sc:   0 },
        { label: 'MESA Bonaerense (Prov.)',                   si:   0, ing: 5081.05, eg: 5081.05, sc:   0 },
        { label: 'Fondo Educativo Ley 26.075 (Prov.)',        si:   0, ing: 5911.35, eg: 5911.35, sc:   0 },
        { label: 'Fort. Seguridad Bonaerense (Prov.)',        si:   0, ing: 1659.00, eg: 1659.00, sc:   0 },
        { label: 'Fort. Programas Sociales (Prov.)',          si:   0, ing: 1001.53, eg: 1001.53, sc:   0 },
        { label: 'Desarrollo Urbano Ord. 3690 (Mpal.)',       si:   0, ing:  586.00, eg:  586.00, sc:   0 },
        { label: 'Derechos Construcción Ord. 3440 (Mpal.)',   si:   0, ing:  870.00, eg:  870.00, sc:   0 },
        { label: 'Estacionamiento Medido Ord. 3494 (Mpal.)',  si:   0, ing: 1159.20, eg: 1159.20, sc:   0 },
      ],
    },


    gastos: {
      total:           150745.28,
      pagado:          142314.28,
      deudaFlotante:     8431.00,
      alertaPrincipal: 'El <strong>gasto en personal</strong> aumentó un 56% nominal (+0,5% real). El <strong>servicio de la deuda</strong> creció +234% nominal (+81% real) — de $1.667 M a $5.628 M — el ítem de mayor alerta para 2027.',
      porObjeto: [
        { label: 'Gastos en personal',      val: 41274.15, pct: 27.4, impago:    0,    color: 'rgba(13,148,136,.65)'  },
        { label: 'Servicios no personales', val: 67407.23, pct: 44.7, impago: 5800,    color: 'rgba(220,38,38,.65)'   },
        { label: 'Bienes de uso (capital)', val: 15392.61, pct: 10.2, impago: 1200,    color: 'rgba(234,88,12,.65)'   },
        { label: 'Transferencias',          val: 14676.92, pct:  9.7, impago:  900,    color: 'rgba(37,99,235,.65)'   },
        { label: 'Servicio de la deuda',    val:  5627.82, pct:  3.7, impago:    0,    color: 'rgba(124,58,237,.65)'  },
        { label: 'Bienes de consumo',       val:  5858.89, pct:  3.9, impago:  531,    color: 'rgba(217,119,6,.65)'   },
        { label: 'Activos financieros',     val:   507.66, pct:  0.3, impago:    0,    color: 'rgba(100,116,139,.65)' },
      ],
      programas: [
        // TODOS los programas 2025 — datos exactos RAFAM · Ejecución por Categoría Programática
        { label: 'Higiene Urbana y Control Microbasurales',    val: 38473.68, sec: 'Ambiente' },
        { label: 'Obras Viales',                               val: 10304.54, sec: 'Obras Púb.' },
        { label: 'Coordinación Políticas Económicas',          val:  7020.31, sec: 'Finanzas' },
        { label: 'Administración General (Seguridad)',          val:  5489.63, sec: 'Seguridad' },
        { label: 'Administración General (Cap. Humano)',        val:  5528.11, sec: 'Capital Humano' },
        { label: 'Deuda Flotante',                             val:  5540.40, sec: 'Deuda' },
        { label: 'Servicio Alimentario Escolar (SAE)',          val:  4765.49, sec: 'Capital Humano' },
        { label: 'Administración General (Salud)',              val:  4980.39, sec: 'Salud' },
        { label: 'MESA Bonaerense',                            val:  5194.27, sec: 'Capital Humano' },
        { label: 'Administración General (Obras Púb.)',         val:  3102.56, sec: 'Obras Púb.' },
        { label: 'Fort. Sistema Atención Primaria',            val:  3113.83, sec: 'Salud' },
        { label: 'Emergencia Social y Seg. Alimentaria',       val:  2869.73, sec: 'Capital Humano' },
        { label: 'Administración General (Coord.)',             val:  2551.44, sec: 'Coord. Gabinete' },
        { label: 'Fort. Sistema Protección Ciudadana',         val:  2597.98, sec: 'Seguridad' },
        { label: 'Fort. Infraestructura Educativa',            val:  2561.14, sec: 'Capital Humano' },
        { label: 'Administración General (Sec. Gral.)',         val:  2683.92, sec: 'Sec. General' },
        { label: 'Mantenimiento Sistema Alumbrado',            val:  2202.77, sec: 'Ambiente' },
        { label: 'Formación y Sanción de Ordenanzas (HCD)',    val:  2776.72, sec: 'HCD' },
        { label: 'Coordinación Servicios Informáticos',        val:  1953.74, sec: 'Finanzas' },
        { label: 'Administración General (Ambiente)',           val:  1841.73, sec: 'Ambiente' },
        { label: 'Obras de Infraestructura',                   val:  1734.70, sec: 'Obras Púb.' },
        { label: 'Administración General (Trabajo)',            val:  1721.47, sec: 'Trabajo' },
        { label: 'Fort. Espacios Públicos',                    val:  1547.73, sec: 'Ambiente' },
        { label: 'Servicios Generales (Obras)',                val:  1438.12, sec: 'Obras Púb.' },
        { label: 'Primera Infancia y Jardines Municipales',    val:  1466.94, sec: 'Capital Humano' },
        { label: 'Plan Anual Seguridad e Higiene',             val:  1560.16, sec: 'Trabajo' },
        { label: 'Fort. Sistema Atención Médica (SAME)',       val:  1256.29, sec: 'Salud' },
        { label: 'Coordinación y Adm. de Ingresos',            val:  1263.38, sec: 'Finanzas' },
        { label: 'Arbolado Público',                           val:  1083.86, sec: 'Ambiente' },
        { label: 'Promoción Cultural y Patrimonial',           val:  1013.25, sec: 'Capital Humano' },
        { label: 'Protección y Restitución Derechos NNA',      val:   892.44, sec: 'Capital Humano' },
        { label: 'Recursos Humanos (Finanzas)',                 val:   835.78, sec: 'Finanzas' },
        { label: 'Coordinación y Adm. de Gastos (Sec. Gral.)', val:   752.43, sec: 'Sec. General' },
        { label: 'Fort. Hospital Odontológico',                val:   639.80, sec: 'Salud' },
        { label: 'Comunicación y Contenido',                   val:   760.87, sec: 'Coord. Gabinete' },
        { label: 'Prensa y Comunicación',                      val:   767.24, sec: 'Coord. Gabinete' },
        { label: 'Fort. y Apoyo Deportistas y Clubes',         val:   564.08, sec: 'Capital Humano' },
        { label: 'Economía Social y Popular',                  val:   579.91, sec: 'Capital Humano' },
        { label: 'Fort. Hospital Oftalmológico',               val:   557.80, sec: 'Salud' },
        { label: 'Deporte Educativo',                          val:   548.28, sec: 'Capital Humano' },
        { label: 'Ord. Centralidades y Estacionamiento',       val:   521.19, sec: 'Obras Púb.' },
        { label: 'Plan Urbano Estratégico',                    val:   498.82, sec: 'Obras Púb.' },
        { label: 'Plan Integral Ordenamiento Esp. Público',    val:   419.54, sec: 'Trabajo' },
        { label: 'Coordinación y Adm. de Gastos (Finanzas)',   val:   453.32, sec: 'Finanzas' },
        { label: 'Plan Regularización Dominial Altos Podestá', val:   401.29, sec: 'Capital Humano' },
        { label: 'Ligas Deportivas y Juegos Bonaerenses',      val:   380.63, sec: 'Capital Humano' },
        { label: 'Determinantes Sociales de la Salud',         val:   388.94, sec: 'Salud' },
        { label: 'Coordinación Sistema Seguridad Local',       val:   321.73, sec: 'Seguridad' },
        { label: 'Legal y Técnica',                            val:   314.01, sec: 'Sec. General' },
        { label: 'Coordinación General de la Gestión',        val:   316.28, sec: 'Coord. Gabinete' },
        { label: 'Red Pública Salud AMBA',                     val:   269.22, sec: 'Salud' },
        { label: 'Programa de Hábitat Sustentable',            val:   264.73, sec: 'Capital Humano' },
        { label: 'Gestión Integral Habilitaciones',            val:   257.34, sec: 'Trabajo' },
        { label: 'Bacheo y Repavimentación',                   val:   254.77, sec: 'Obras Púb.' },
        { label: 'Asuntos Institucionales (Sec. Gral.)',        val:   232.71, sec: 'Sec. General' },
        { label: 'Fort. Programas Sanitarios',                 val:   230.74, sec: 'Salud' },
        { label: 'Fondo Infraestructura Municipal (FIM)',      val:   204.38, sec: 'Obras Púb.' },
        { label: 'Fort. Escuelas Municipales',                 val:   198.40, sec: 'Capital Humano' },
        { label: 'Puesta en Valor Espacios Verdes',            val:   191.74, sec: 'Obras Púb.' },
        { label: 'Administración General (Territorial)',        val:   163.65, sec: 'Territorial' },
        { label: 'Epidemiología y Control de Vectores',        val:   154.98, sec: 'Salud' },
        { label: 'Formación para el Trabajo y Teletrabajo',    val:   145.20, sec: 'Trabajo' },
        { label: 'Defensa al Consumidor (Coord.)',             val:   140.99, sec: 'Coord. Gabinete' },
        { label: 'Red Secundaria Cloacal Loma Hermosa OC70291',val:   138.46, sec: 'Capital Humano' },
        { label: 'Centro Educativo Ambiental',                 val:   119.66, sec: 'Ambiente' },
        { label: 'Red Cloacal Loma Hermosa OC70291 (Des. Hum.)',val:  109.45, sec: 'Des. Humano' },
        { label: 'Programa Inclusión Personas c/ Discapacidad', val:  109.50, sec: 'Capital Humano' },
        { label: 'Gobierno Cercano y Accesible (Coord.)',      val:   646.33, sec: 'Coord. Gabinete' },
        { label: 'Administración General (Gob.)',               val:   166.21, sec: 'Sec. Gobierno' },
        { label: 'Fort. e Infr. Centros Deportivos',           val:   189.77, sec: 'Capital Humano' },
        { label: 'Administración General (Des. Humano)',        val:   189.26, sec: 'Des. Humano' },
        { label: 'Emergencia Social (residual Des. Humano)',    val:   186.12, sec: 'Des. Humano' },
        { label: 'Géneros, Diversidad y DDHH',                 val:   181.15, sec: 'Capital Humano' },
        { label: 'Espacios Comunitarios Territoriales',        val:   180.72, sec: 'Capital Humano' },
        { label: 'Administración General (Control)',            val:    50.85, sec: 'Control Mpal.' },
        { label: 'Plan Anual Seg. e Higiene (Control)',        val:    88.87, sec: 'Control Mpal.' },
        { label: 'Plan Ord. Esp. Públ. (Control)',             val:    30.10, sec: 'Control Mpal.' },
        { label: 'Gestión Habilitaciones (Control)',           val:    20.05, sec: 'Control Mpal.' },
        { label: 'Administración General (At. Vecino)',         val:    80.34, sec: 'At. Vecino' },
        { label: 'Gobierno Cercano y Accesible (At. Vecino)',   val:    13.62, sec: 'At. Vecino' },
        { label: 'Defensa al Consumidor (At. Vecino)',         val:     2.92, sec: 'At. Vecino' },
        { label: 'Ord. Centralidades (Territorial)',           val:    18.45, sec: 'Territorial' },
        { label: 'Plan Integral Movilidad (Territorial)',      val:     7.15, sec: 'Territorial' },
        { label: 'Licencias de Conducir (Obras)',              val:   283.74, sec: 'Obras Púb.' },
        { label: 'Desarrollo Urbano y Hábitat Sustentable',    val:    43.14, sec: 'Obras Púb.' },
        { label: 'Casa Propia - Construir Futuro',             val:    68.58, sec: 'Obras Púb.' },
        { label: 'Plan Integral Movilidad (Obras)',            val:     6.68, sec: 'Obras Púb.' },
        { label: 'Juventud (Sec. Gral.)',                       val:   413.21, sec: 'Sec. General' },
        { label: 'Recursos Humanos (Gob.)',                    val:    52.07, sec: 'Sec. Gobierno' },
        { label: 'Juventud (Gob.)',                            val:    36.35, sec: 'Sec. Gobierno' },
        { label: 'Licencias de Conducir (Gob.)',               val:    10.07, sec: 'Sec. Gobierno' },
        { label: 'Asuntos Institucionales (Gob.)',             val:     9.46, sec: 'Sec. Gobierno' },
        { label: 'Deporte Inclusivo',                          val:    59.52, sec: 'Capital Humano' },
        { label: 'Fort. Deportistas (juris. Deporte)',         val:    39.57, sec: 'Capital Humano' },
        { label: 'Deporte Educativo (juris. Deporte)',         val:    48.32, sec: 'Capital Humano' },
        { label: 'Ligas y Juegos (juris. Deporte)',            val:     9.63, sec: 'Capital Humano' },
        { label: 'Fort. CEDEM (juris. Deporte)',               val:     0.49, sec: 'Capital Humano' },
        { label: 'Plazas en Movimiento y Adultos Mayores',     val:    34.81, sec: 'Capital Humano' },
        { label: 'Protección Derechos NNA (residual)',         val:    20.84, sec: 'Des. Humano' },
        { label: 'Economía Social (residual)',                 val:    16.05, sec: 'Des. Humano' },
        { label: 'Inclusión Personas Discapacidad (residual)', val:    10.85, sec: 'Des. Humano' },
        { label: 'Espacios Comunitarios (residual)',           val:     6.59, sec: 'Des. Humano' },
        { label: 'Géneros y DDHH (residual)',                  val:     3.42, sec: 'Des. Humano' },
        { label: 'Red Cloacal Pluvial Vial Churruca',          val:    32.06, sec: 'Capital Humano' },
        { label: 'Red de Agua Potable y Cloaca B° Maldonado', val:    13.74, sec: 'Capital Humano' },
        { label: 'Red Secundaria Cloacal Loma Hermosa OC70094',val:    34.37, sec: 'Capital Humano' },
        { label: 'Programa Familias Solidarias',               val:     8.06, sec: 'Capital Humano' },
        { label: 'Protocolo y Ceremonial',                    val:     2.24, sec: 'Coord. Gabinete' },
        { label: 'Deuda Consolidada',                          val:    27.28, sec: 'Deuda' },
        { label: 'Distribución Innovación y Conocimiento',    val:    59.01, sec: 'Trabajo' },
        { label: 'Desarrollo Centros Comerciales',             val:    55.80, sec: 'Trabajo' },
        { label: 'Programa Puertas Abiertas y Padrinos',      val:    18.88, sec: 'Trabajo' },
        { label: 'Desarrollo Parque Industrial y PYMES',      val:    11.24, sec: 'Trabajo' },
        { label: 'Microcréditos 3FEmprende',                  val:     2.30, sec: 'Trabajo' },
        { label: 'Defensa Civil',                              val:    21.02, sec: 'Seguridad' },
        { label: 'Fort. Sistema Seguridad Vial',               val:    68.85, sec: 'Seguridad' },
        { label: 'Programa Proteger - Min. Salud',             val:     0.31, sec: 'Salud' },
        { label: 'Antropozoonosis',                            val:    69.62, sec: 'Salud' },
        { label: 'Plan SUMAR',                                 val:    47.45, sec: 'Salud' },
        { label: 'Mantenimiento Infr. Sistema Pluvial',        val:    78.07, sec: 'Ambiente' },
        { label: 'Fort. Cementerio Municipal',                 val:    59.47, sec: 'Ambiente' },
      ],
    },

    secretarias: [
      // Datos exactos RAFAM 2025 · Ejecución por Categoría Programática · firmado 20/02/2026
      { label: 'Ambiente y Servicios Públicos', val: 46035.21, nota: 'Higiene Urbana + Alumbrado + Espacios Públicos + Arbolado',
        programas: [
          { label: 'Higiene Urbana y Control Microbasurales',   val: 38473.68 },
          { label: 'Administración General (Ambiente)',          val:  1841.73 },
          { label: 'Mantenimiento Sistema Alumbrado',           val:  2202.77 },
          { label: 'Fort. Espacios Públicos',                   val:  1547.73 },
          { label: 'Arbolado Público',                          val:  1083.86 },
          { label: 'Mantenimiento e Infraestructura Urbana',    val:   628.24 },
          { label: 'Centro Educativo Ambiental',                val:   119.66 },
          { label: 'Mantenimiento Infr. Sistema Pluvial',       val:    78.07 },
          { label: 'Fort. Cementerio Municipal',                val:    59.47 },
        ]
      },
      { label: 'Capital Humano', val: 28518.75, nota: 'Educación + Deporte + Social + Cultura + Habitat', nueva: true,
        programas: [
          { label: 'Administración General (Cap. Humano)',       val:  5528.11 },
          { label: 'MESA Bonaerense',                           val:  5194.27 },
          { label: 'Servicio Alimentario Escolar (SAE)',         val:  4765.49 },
          { label: 'Fort. Infraestructura Educativa',           val:  2561.14 },
          { label: 'Emergencia Social y Seg. Alimentaria',      val:  2869.73 },
          { label: 'Primera Infancia y Jardines Municipales',   val:  1466.94 },
          { label: 'Promoción Cultural y Patrimonial',          val:  1013.25 },
          { label: 'Protección y Restitución Derechos NNA',     val:   892.44 },
          { label: 'Deporte Educativo',                         val:   548.28 },
          { label: 'Fort. y Apoyo Deportistas y Clubes',        val:   564.08 },
          { label: 'Economía Social y Popular',                 val:   579.91 },
          { label: 'Plan Regularización Dominial Altos Podestá',val:   401.29 },
          { label: 'Ligas Deportivas y Juegos Bonaerenses',     val:   380.63 },
          { label: 'Fort. e Infr. Centros Deportivos',          val:   189.77 },
          { label: 'Géneros, Diversidad y DDHH',                val:   181.15 },
          { label: 'Espacios Comunitarios Territoriales',       val:   180.72 },
          { label: 'Programa de Hábitat Sustentable',           val:   264.73 },
          { label: 'Programa Inclusión Personas c/ Discapacidad',val:  109.50 },
          { label: 'Red Secundaria Cloacal Loma Hermosa OC70291',val:  138.46 },
          { label: 'Fort. Escuelas Municipales',                val:   198.40 },
          { label: 'Deporte Inclusivo',                         val:    59.52 },
          { label: 'Fort. CEDEM / Plazas en Movimiento',        val:    34.81 },
          { label: 'Ligas y Juegos (juris. Deporte)',           val:     9.63 },
          { label: 'Fort. Deportistas (juris. Deporte)',        val:    39.57 },
          { label: 'Deporte Educativo (juris. Deporte)',        val:    48.32 },
          { label: 'Red Cloacal Pluvial Vial Churruca',         val:    32.06 },
          { label: 'Red de Agua Potable y Cloaca B° Maldonado', val:    13.74 },
          { label: 'Red Secundaria Cloacal Loma Hermosa OC70094',val:   34.37 },
          { label: 'Programa Familias Solidarias',              val:     8.06 },
        ]
      },
      { label: 'Obras Públicas y Des. Urbano', val: 18652.96, nota: '+235% nominal · Obras Viales + Servicios + Movilidad',
        programas: [
          { label: 'Obras Viales',                              val: 10304.54 },
          { label: 'Administración General (Obras Púb.)',        val:  3102.56 },
          { label: 'Obras de Infraestructura',                  val:  1734.70 },
          { label: 'Servicios Generales (Obras)',                val:  1438.12 },
          { label: 'Ord. Centralidades y Estacionamiento',      val:   521.19 },
          { label: 'Plan Urbano Estratégico',                   val:   498.82 },
          { label: 'Licencias de Conducir (Obras)',             val:   283.74 },
          { label: 'Bacheo y Repavimentación',                  val:   254.77 },
          { label: 'Fondo Infraestructura Municipal (FIM)',     val:   204.38 },
          { label: 'Puesta en Valor Espacios Verdes',           val:   191.74 },
          { label: 'Casa Propia - Construir Futuro',            val:    68.58 },
          { label: 'Desarrollo Urbano y Hábitat Sustentable',   val:    43.14 },
          { label: 'Plan Integral Movilidad (Obras)',           val:     6.68 },
        ]
      },
      { label: 'Secretaría de Salud', val: 11709.37, nota: 'Atención primaria + SAME + Hospitales',
        programas: [
          { label: 'Administración General (Salud)',             val:  4980.39 },
          { label: 'Fort. Sistema Atención Primaria',           val:  3113.83 },
          { label: 'Fort. Sistema Atención Médica (SAME)',      val:  1256.29 },
          { label: 'Fort. Hospital Odontológico',               val:   639.80 },
          { label: 'Fort. Hospital Oftalmológico',              val:   557.80 },
          { label: 'Determinantes Sociales de la Salud',        val:   388.94 },
          { label: 'Red Pública Salud AMBA',                    val:   269.22 },
          { label: 'Fort. Programas Sanitarios',                val:   230.74 },
          { label: 'Epidemiología y Control de Vectores',       val:   154.98 },
          { label: 'Antropozoonosis',                           val:    69.62 },
          { label: 'Plan SUMAR',                                val:    47.45 },
          { label: 'Programa Proteger - Min. Salud',            val:     0.31 },
        ]
      },
      { label: 'Finanzas y Eficiencia del Estado', val: 11526.53, nota: 'Políticas económicas + Ingresos + Informática + RRHH',
        programas: [
          { label: 'Coordinación Políticas Económicas',         val:  7020.31 },
          { label: 'Coordinación Servicios Informáticos',       val:  1953.74 },
          { label: 'Coordinación y Adm. de Ingresos',           val:  1263.38 },
          { label: 'Recursos Humanos (Finanzas)',                val:   835.78 },
          { label: 'Coordinación y Adm. de Gastos',             val:   453.32 },
        ]
      },
      { label: 'Secretaría de Seguridad', val: 10118.49, nota: 'Protección ciudadana + Video vigilancia + Defensa Civil',
        programas: [
          { label: 'Administración General (Seguridad)',         val:  5489.63 },
          { label: 'Fort. Sistema Protección Ciudadana',        val:  2597.98 },
          { label: 'Fort. Sistema Video Vigilancia',            val:   941.98 },
          { label: 'Centro Atención a las Víctimas',            val:   677.30 },
          { label: 'Coordinación Sistema Seguridad Local',      val:   321.73 },
          { label: 'Fort. Sistema Seguridad Vial',              val:    68.85 },
          { label: 'Defensa Civil',                             val:    21.02 },
        ]
      },
      { label: 'Servicio de la Deuda', val: 5567.68, nota: '+234% nominal vs 2024',
        programas: [
          { label: 'Deuda Flotante',                            val:  5540.40 },
          { label: 'Deuda Consolidada',                         val:    27.28 },
        ]
      },
      { label: 'Coordinación de Gabinete', val: 5185.39, nota: 'Nueva · Comunicación + Coord. + Atención al Vecino', nueva: true,
        programas: [
          { label: 'Administración General (Coord.)',            val:  2551.44 },
          { label: 'Comunicación y Contenido',                  val:   760.87 },
          { label: 'Prensa y Comunicación',                     val:   767.24 },
          { label: 'Gobierno Cercano y Accesible',              val:   646.33 },
          { label: 'Coordinación General de la Gestión',        val:   316.28 },
          { label: 'Defensa al Consumidor (Coord.)',             val:   140.99 },
          { label: 'Protocolo y Ceremonial',                    val:     2.24 },
        ]
      },
      { label: 'Trabajo y Producción', val: 4250.94, nota: '+464% nominal vs 2024 · incluye Plan Seg. e Higiene',
        programas: [
          { label: 'Administración General (Trabajo)',           val:  1721.47 },
          { label: 'Plan Anual Seguridad e Higiene',            val:  1560.16 },
          { label: 'Plan Integral Ordenamiento Esp. Público',   val:   419.54 },
          { label: 'Gestión Integral Habilitaciones',           val:   257.34 },
          { label: 'Formación para el Trabajo y Teletrabajo',   val:   145.20 },
          { label: 'Desarrollo Centros Comerciales',            val:    55.80 },
          { label: 'Distrito Innovación y Conocimiento',        val:    59.01 },
          { label: 'Desarrollo Parque Industrial y PYMES',      val:    11.24 },
          { label: 'Programa Puertas Abiertas y Padrinos',      val:    18.88 },
          { label: 'Microcréditos 3FEmprende',                  val:     2.30 },
        ]
      },
      { label: 'Secretaría General', val: 4396.28, nota: 'Administración + Legal + Juventud + RRHH',
        programas: [
          { label: 'Administración General (Sec. Gral.)',        val:  2683.92 },
          { label: 'Coordinación y Adm. de Gastos',             val:   752.43 },
          { label: 'Juventud',                                   val:   413.21 },
          { label: 'Legal y Técnica',                           val:   314.01 },
          { label: 'Asuntos Institucionales',                   val:   232.71 },
        ]
      },
      { label: 'H.C.D.', val: 2776.72, nota: '',
        programas: [
          { label: 'Formación y Sanción de Ordenanzas',         val:  2776.72 },
        ]
      },
      { label: 'Juzgado de Faltas', val: 712.74, nota: '',
        programas: [
          { label: 'Administración General (Juzgado Faltas)',    val:   712.74 },
        ]
      },
      { label: 'Des. Humano y Hábitat', val: 542.58, nota: 'Jurisdicción residual — mayoría reasignada a Capital Humano',
        programas: [
          { label: 'Administración General (Des. Humano)',       val:   189.26 },
          { label: 'Emergencia Social (residual)',               val:   186.12 },
          { label: 'Red Cloacal Loma Hermosa OC70291 (residual)',val:   109.45 },
          { label: 'Protección Derechos NNA (residual)',         val:    20.84 },
          { label: 'Economía Social (residual)',                 val:    16.05 },
          { label: 'Inclusión Personas Discapacidad (residual)', val:    10.85 },
          { label: 'Espacios Comunitarios (residual)',           val:     6.59 },
          { label: 'Géneros y DDHH (residual)',                  val:     3.42 },
        ]
      },
      { label: 'Sec. de Gobierno', val: 274.16, nota: 'Funciones reasignadas · jurisdicción residual',
        programas: [
          { label: 'Administración General (Gob.)',              val:   166.21 },
          { label: 'Recursos Humanos (Gob.)',                    val:    52.07 },
          { label: 'Juventud (Gob.)',                           val:    36.35 },
          { label: 'Licencias de Conducir (Gob.)',              val:    10.07 },
          { label: 'Asuntos Institucionales (Gob.)',            val:     9.46 },
        ]
      },
      { label: 'Control Municipal', val: 189.87, nota: 'Funciones fusionadas en Trabajo y Producción',
        programas: [
          { label: 'Plan Anual Seguridad e Higiene (Control)',   val:    88.87 },
          { label: 'Administración General (Control)',           val:    50.85 },
          { label: 'Plan Integral Ord. Esp. Públ. (Control)',   val:    30.10 },
          { label: 'Gestión Habilitaciones (Control)',          val:    20.05 },
        ]
      },
      { label: 'Des. Territorial y Movilidad', val: 189.25, nota: '−91,5% real vs 2024 · funciones reasignadas a Obras Públicas',
        programas: [
          { label: 'Administración General (Territorial)',       val:   163.65 },
          { label: 'Ord. Centralidades (Territorial)',           val:    18.45 },
          { label: 'Plan Integral Movilidad (Territorial)',     val:     7.15 },
        ]
      },
      { label: 'Atención al Vecino', val: 96.88, nota: 'Funciones reasignadas a Coordinación',
        programas: [
          { label: 'Administración General (At. Vecino)',        val:    80.34 },
          { label: 'Gobierno Cercano y Accesible (At. Vecino)',  val:    13.62 },
          { label: 'Defensa al Consumidor (At. Vecino)',         val:     2.92 },
        ]
      },
    ],
    personal: {
      total: 2798,
      permanente: 1110,
      mensualizado: 1688,
      gastoTotal: 41274.15,
      paritaria: 25,  // 25% acumulado 2025
      porSecretaria: [
        { label: 'Educación y Cultura (Capital Humano)', val: 541 },
        { label: 'Salud',                                val: 530 },
        { label: 'Seguridad',                            val: 528 },
        { label: 'Obras Públicas',                       val: 250 },
        { label: 'Trabajo y Producción',                 val: 207 },
        { label: 'Ambiente y Serv. Públicos',            val: 205 },
        { label: 'Jefatura de Gabinete',                 val: 151 },
        { label: 'Finanzas y Efic. del Estado',          val: 129 },
        { label: 'Secretaría General',                   val: 117 },
        { label: 'HCD',                                  val: 117 },
        { label: 'Juzgado de Faltas',                    val:  23 },
      ],
      componentes: [
        { label: 'Retribuciones del cargo (perm. + temp.)', val: 19200 },
        { label: 'Horas extras',                            val:  3800 },
        { label: 'Contribuciones patronales',               val:  6100 },
        { label: 'SAC',                                     val:  3200 },
        { label: 'Otras bonificaciones + complementos',     val:  5800 },
        { label: 'DIPREGEP + Asig. familiares + otros',     val:  3174 },
      ],
    },
  },

  /* ─────────────── 2026 ─────────────── */
  2026: {
    status: 'partial',
    fuente: 'RAFAM · Ejecución al 31/03/2026 · Datos reales por jurisdicción y apertura programática · Anualizados ×4 (deuda: Q1 real)',
    ipc: 0.30,
    nota: 'Datos Q1 2026 (2094 registros RAFAM). Todo ×4 excepto Servicio de la Deuda (Q1 real: $8.430 M, incluye deuda flotante 2025 concentrada en Q1).',

    resumen: {
      ejecutado:      141391.09,
      percibido:      182529.40,
      presupAprobado: 189429.89,
      superavitArt43: null,
      resultadoArt44: null,
      saldoCajaIni:   30733.66,
      saldoCajaFin:    9221.69,
      deudaFlotante:  null,
      ingCorrientes:  182396.28,
      gasCorrientes:  132961.40,
      ahorroCorriente: 49434.88,
      recursosCapital:   133.13,
      gastosCapital:   10122.12,
      paritaria: null,
    },

    recursos: {
      totalDevengado:  207935.63,
      totalPercibido:  182529.40,
      origenMunicipal: 124349.00,
      origenProvincial: 57846.00,
      origenNacional:    333.30,
      tipos: [
        { label: 'Tasas municipales (est.)',          val: 99739.16 },
        { label: 'Coparticipación + trib. (est.)',    val: 56059.08 },
        { label: 'Transferencias corrientes (est.)',  val: 16193.52 },
        { label: 'Rentas propiedad (intereses)',       val:  2173.96 },
        { label: 'Multas y derechos',                 val:  5645.49 },
        { label: 'Venta bienes y servicios',          val:     0.00 },
        { label: 'Recursos propios de capital',       val:   133.13 },
      ],
      tasas: [
        { label: 'Insp. Seg. e Higiene (TISH)',       val: 35617.64 },
        { label: 'Servicios Generales',               val: 62837.00 },
        { label: 'Patente Automotores + Rodados',     val:  2094.55 },
        { label: 'Estacionamiento Medido',            val:  1139.34 },
      ],
      tributarios: [
        { label: 'Coparticipación Pcial. Ley 10.559 (est.)', val: 132587.60, orig: 'Provincial' },
        { label: 'Canon EDENOR (est.)',                       val:  24165.76, orig: 'Municipal'  },
        { label: 'Fondo Mpal. Inclusión Social L.13863',      val:   3199.02, orig: 'Provincial' },
        { label: 'Fondo Fort. Recursos Municipales',          val:   2447.23, orig: 'Provincial' },
        { label: 'CEAMSE - Recepción Residuos',               val:   7107.00, orig: 'Municipal'  },
      ],
      fondos: [],
    },

    gastos: {
      total:          141391.09,
      pagado:         137612.14,
      deudaFlotante:  null,
      alertaPrincipal: 'Datos <strong>provisorios al 31/03/2026 (2094 registros RAFAM), anualizados ×4</strong>. El servicio de la deuda ($8.430 M) es el dato Q1 real sin anualizar — incluye pago de deuda flotante 2025 concentrado en Q1.',
      porObjeto: [
        { label: 'Gastos en personal',      val: 46439.72, pct: 32.8, impago: 0,       color: 'rgba(13,148,136,.65)'  },
        { label: 'Servicios no personales', val: 62700.52, pct: 44.3, impago: 0,       color: 'rgba(220,38,38,.65)'   },
        { label: 'Transferencias',          val:  8190.96, pct:  5.8, impago: 0,       color: 'rgba(37,99,235,.65)'   },
        { label: 'Bienes de uso (capital)', val: 10122.12, pct:  7.2, impago: 0,       color: 'rgba(234,88,12,.65)'   },
        { label: 'Bienes de consumo',       val:  4744.72, pct:  3.4, impago: 0,       color: 'rgba(217,119,6,.65)'   },
        { label: 'Activos financieros',     val:   763.36, pct:  0.5, impago: 0,       color: 'rgba(124,58,237,.65)'  },
        { label: 'Servicio de la deuda (*)',val:  8429.69, pct:  6.0, impago: 0,       color: 'rgba(100,116,139,.65)' },
      ],
      programas: [
        { label: 'Higiene Urbana y Control de Microbasurales',        val: 44027.72, sec: 'Ambiente'        },
        { label: 'Administración General (Obras Púb.)',                val: 11729.20, sec: 'Obras Púb.'      },
        { label: 'Amortización deuda interna (flotante 2025 + propia)',val:  8429.69, sec: 'Deuda'           },
        { label: 'Administración General (Cap. Humano)',               val:  5737.20, sec: 'Capital Humano'  },
        { label: 'Fort. Sistema Atención Primaria',                    val:  5252.12, sec: 'Salud'           },
        { label: 'Plan Anual Seg., Higiene y Ord. Esp. Púb.',         val:  2779.60, sec: 'Trabajo'         },
        { label: 'Administración General (Sec. General)',              val:  3066.52, sec: 'Sec. General'    },
        { label: 'Emergencia Social y Seg. Alimentaria',               val:  3178.44, sec: 'Capital Humano'  },
        { label: 'Primera Infancia y Jardines de Infantes',            val:  2371.92, sec: 'Capital Humano'  },
        { label: 'Administración General (Salud)',                     val:  2509.96, sec: 'Salud'           },
        { label: 'Servicios Generales (Obras Púb.)',                   val:  2470.52, sec: 'Obras Púb.'      },
        { label: 'Fort. Infraestructura Educativa',                    val:  2147.80, sec: 'Capital Humano'  },
        { label: 'MESA Bonaerense',                                    val:  2078.20, sec: 'Capital Humano'  },
        { label: 'Fort. Complejo Hospitalario',                        val:  2047.48, sec: 'Salud'           },
        { label: 'Fort. Sistema Protección Ciudadana',                 val:  2514.32, sec: 'Seguridad'       },
        { label: 'Administración General (Seguridad)',                 val:  3092.00, sec: 'Seguridad'       },
        { label: 'Niñez, Adolescencia y Familia',                      val:  1667.64, sec: 'Capital Humano'  },
        { label: 'Hábitat, Vivienda y Regularización Dominial',        val:  1604.64, sec: 'Capital Humano'  },
        { label: 'Promoción Cultural y Patrimonial',                   val:  1589.24, sec: 'Capital Humano'  },
        { label: 'Fort. Sistema Atención Médica (SAME)',               val:  1315.24, sec: 'Salud'           },
        { label: 'Fort. Sistema Video Vigilancia',                     val:  1436.52, sec: 'Seguridad'       },
        { label: 'Desarrollo Deportivo y Apoyo a Clubes',              val:  1231.76, sec: 'Capital Humano'  },
        { label: 'SAE - Servicio Alimentario Escolar',                 val:  1043.04, sec: 'Capital Humano'  },
        { label: 'Administración General (Finanzas)',                  val:  1888.56, sec: 'Finanzas'        },
        { label: 'Administración General (Coordinación)',              val:  1166.08, sec: 'Coordinación'    },
        { label: 'Coordinación y Adm. Ingresos Públicos',             val:  1641.48, sec: 'Finanzas'        },
        { label: 'Administración General (Ambiente)',                  val:  1235.60, sec: 'Ambiente'        },
        { label: 'Fort. Centro Especialidades (CEMAR)',                val:   892.28, sec: 'Salud'           },
        { label: 'Gobierno Cercano y Accesible',                       val:  1513.12, sec: 'Coordinación'    },
        { label: 'Coordinación y Adm. Modernización',                 val:  1253.92, sec: 'Finanzas'        },
        { label: 'Fort. Instituciones Educativas',                     val:   685.80, sec: 'Capital Humano'  },
        { label: 'Coordinación y Adm. Recursos Humanos',              val:  1100.40, sec: 'Finanzas'        },
        { label: 'Coordinación y Adm. Finanzas',                      val:   770.00, sec: 'Finanzas'        },
        { label: 'Comunicación y Prensa',                              val:  1227.68, sec: 'Sec. General'    },
        { label: 'Formación y Sanción de las Ordenanzas',             val:   684.17, sec: 'HCD'             },
        { label: 'Fort. Sistema Seguridad Vial',                       val:   858.20, sec: 'Seguridad'       },
        { label: 'Plan Integral de Movilidad',                         val:   715.40, sec: 'Obras Púb.'      },
        { label: 'Coordinación y Adm. de Gastos',                     val:   893.76, sec: 'Sec. General'    },
        { label: 'Servicios Seguridad y Emergencias',                  val:  1218.04, sec: 'Seguridad'       },
        { label: 'Determinantes Sociales de la Salud',                 val:   524.48, sec: 'Salud'           },
        { label: 'Deporte en el Espacio Público',                      val:   511.16, sec: 'Capital Humano'  },
        { label: 'Planificación Seguridad Local',                      val:   449.60, sec: 'Seguridad'       },
        { label: 'Fort. Inversiones y Emprendedores',                 val:   490.20, sec: 'Trabajo'         },
        { label: 'Desarrollo Urbano y Hábitat Sustentable',           val:   570.24, sec: 'Obras Púb.'      },
        { label: 'Center Atención a las Víctimas',                     val:   360.16, sec: 'Seguridad'       },
        { label: 'Coordinación General de la Gestión',                val:   348.88, sec: 'Coordinación'    },
        { label: 'Fort. Cementerio Municipal',                         val:   321.32, sec: 'Ambiente'        },
        { label: 'Administración General (Trabajo)',                   val:   803.04, sec: 'Trabajo'         },
        { label: 'Licencias de Conducir',                              val:   333.28, sec: 'Obras Púb.'      },
        { label: 'Administración General (Juzgado Faltas)',            val:   819.68, sec: 'Juzgado Faltas'  },
        { label: 'Formación para el Trabajo y Teletrabajo',           val:   279.84, sec: 'Trabajo'         },
        { label: 'Programa de Salud Mental',                           val:   247.44, sec: 'Salud'           },
        { label: 'Desarrollo Comercial y Prom. Industrial',           val:   156.52, sec: 'Trabajo'         },
        { label: 'Legal y Técnica',                                    val:   884.96, sec: 'Sec. General'    },
        { label: 'Asuntos Institucionales',                            val:   292.88, sec: 'Sec. General'    },
        { label: 'Ordenamiento de Centralidades',                     val:   119.40, sec: 'Obras Púb.'      },
        { label: 'Juventud',                                           val:   308.88, sec: 'Sec. General'    },
        { label: 'Plan Urbano Estratégico',                            val:    87.16, sec: 'Obras Púb.'      },
        { label: 'Espacios Comunitarios Territoriales',                val:    81.96, sec: 'Capital Humano'  },
        { label: 'Protocolo y Ceremonial',                             val:   162.56, sec: 'Coordinación'    },
        { label: 'Ligas Deportivas y Juegos Bonaerenses',             val:    66.16, sec: 'Capital Humano'  },
        { label: 'Distrito Innovación y Conocimiento',                val:    26.16, sec: 'Trabajo'         },
        { label: 'Desarrollo Parque Industrial',                       val:    18.12, sec: 'Trabajo'         },
        { label: 'Programa SUMAR',                                     val:     4.00, sec: 'Salud'           },
        { label: 'Microcréditos 3F Emprende',                         val:     4.80, sec: 'Trabajo'         },
      ],
    },

    secretarias: [
      { label: 'Ambiente y Servicios Públicos', val: 45584.64, nota: 'Higiene Urbana + Adm. General + Cementerio — Q1×4',
        programas: [
          { label: 'Higiene Urbana y Control de Microbasurales',  val: 44027.72 },
          { label: 'Administración General (Ambiente)',            val:  1235.60 },
          { label: 'Fort. Cementerio Municipal',                   val:   321.32 },
        ]
      },
      { label: 'Servicio de la Deuda', val: 8429.69, nota: 'Dato Q1 real sin anualizar — incluye deuda flotante 2025',
        programas: [
          { label: 'Amortización deuda interna (flotante 2025 + propia)', val: 8429.39 },
          { label: 'Deuda Consolidada',                                    val:    0.30 },
        ]
      },
      { label: 'Capital Humano', val: 23995.12, nota: 'SAE + MESA + Educativa + Social + Cultura + Deporte — Q1×4', nueva25: true,
        programas: [
          { label: 'Administración General (Cap. Humano)',         val:  5737.20 },
          { label: 'Emergencia Social y Seg. Alimentaria',         val:  3178.44 },
          { label: 'Primera Infancia y Jardines de Infantes',      val:  2371.92 },
          { label: 'Fort. Infraestructura Educativa',              val:  2147.80 },
          { label: 'MESA Bonaerense',                              val:  2078.20 },
          { label: 'Niñez, Adolescencia y Familia',                val:  1667.64 },
          { label: 'Hábitat, Vivienda y Reg. Dominial',            val:  1604.64 },
          { label: 'Promoción Cultural y Patrimonial',             val:  1589.24 },
          { label: 'Desarrollo Deportivo y Apoyo a Clubes',        val:  1231.76 },
          { label: 'SAE - Servicio Alimentario Escolar',           val:  1043.04 },
          { label: 'Fort. Instituciones Educativas',               val:   685.80 },
          { label: 'Deporte en el Espacio Público',                val:   511.16 },
          { label: 'Espacios Comunitarios Territoriales',          val:    81.96 },
          { label: 'Ligas Deportivas y Juegos Bonaerenses',        val:    66.16 },
        ]
      },
      { label: 'Obras Públicas y Des. Urbano', val: 16025.20, nota: 'Adm. General + Servicios Generales + Movilidad — Q1×4',
        programas: [
          { label: 'Administración General (Obras Púb.)',          val: 11729.20 },
          { label: 'Servicios Generales',                          val:  2470.52 },
          { label: 'Plan Integral de Movilidad',                   val:   715.40 },
          { label: 'Desarrollo Urbano y Hábitat Sustentable',      val:   570.24 },
          { label: 'Licencias de Conducir',                        val:   333.28 },
          { label: 'Ordenamiento de Centralidades',                val:   119.40 },
          { label: 'Plan Urbano Estratégico',                      val:    87.16 },
        ]
      },
      { label: 'Secretaría de Salud', val: 12793.00, nota: 'APS + Hospitalario + SAME + CEMAR — Q1×4',
        programas: [
          { label: 'Fort. Sistema Atención Primaria',              val:  5252.12 },
          { label: 'Administración General (Salud)',               val:  2509.96 },
          { label: 'Fort. Complejo Hospitalario',                  val:  2047.48 },
          { label: 'Fort. Sistema Atención Médica (SAME)',         val:  1315.24 },
          { label: 'Fort. Centro Especialidades (CEMAR)',          val:   892.28 },
          { label: 'Determinantes Sociales de la Salud',           val:   524.48 },
          { label: 'Programa de Salud Mental',                     val:   247.44 },
          { label: 'Programa SUMAR',                               val:     4.00 },
        ]
      },
      { label: 'Secretaría de Seguridad', val: 9928.88, nota: 'Q1×4',
        programas: [
          { label: 'Administración General (Seguridad)',           val:  3092.00 },
          { label: 'Fort. Sistema Protección Ciudadana',           val:  2514.32 },
          { label: 'Fort. Sistema Video Vigilancia',               val:  1436.52 },
          { label: 'Servicios Seguridad y Emergencias',            val:  1218.04 },
          { label: 'Fort. Sistema Seguridad Vial',                 val:   858.20 },
          { label: 'Planificación Seguridad Local',                val:   449.60 },
          { label: 'Center Atención a las Víctimas',               val:   360.16 },
        ]
      },
      { label: 'Secretaría General', val: 6674.68, nota: 'Adm. General + Comunicación + Legal + Juventud — Q1×4',
        programas: [
          { label: 'Administración General (Sec. General)',        val:  3066.52 },
          { label: 'Comunicación y Prensa',                        val:  1227.68 },
          { label: 'Coordinación y Adm. de Gastos',               val:   893.76 },
          { label: 'Legal y Técnica',                              val:   884.96 },
          { label: 'Juventud',                                     val:   308.88 },
          { label: 'Asuntos Institucionales',                      val:   292.88 },
        ]
      },
      { label: 'Finanzas y Efic. del Estado', val: 6654.36, nota: 'Q1×4',
        programas: [
          { label: 'Administración General (Finanzas)',            val:  1888.56 },
          { label: 'Coordinación y Adm. Ingresos Públicos',       val:  1641.48 },
          { label: 'Coordinación y Adm. Modernización',           val:  1253.92 },
          { label: 'Coordinación y Adm. Recursos Humanos',        val:  1100.40 },
          { label: 'Coordinación y Adm. Finanzas',                val:   770.00 },
        ]
      },
      { label: 'Trabajo y Producción', val: 4558.24, nota: 'Q1×4',
        programas: [
          { label: 'Plan Anual Seg., Higiene y Ord. Esp. Púb.',   val:  2779.60 },
          { label: 'Administración General (Trabajo)',             val:   803.04 },
          { label: 'Fort. Inversiones y Emprendedores',           val:   490.20 },
          { label: 'Formación para el Trabajo y Teletrabajo',     val:   279.84 },
          { label: 'Desarrollo Comercial y Prom. Industrial',     val:   156.52 },
          { label: 'Distrito Innovación y Conocimiento',          val:    26.16 },
          { label: 'Desarrollo Parque Industrial',                 val:    18.12 },
          { label: 'Microcréditos 3F Emprende',                   val:     4.80 },
        ]
      },
      { label: 'Secretaría de Coordinación', val: 3190.64, nota: 'Gobierno Cercano + Coord. Gestión — Q1×4',
        programas: [
          { label: 'Gobierno Cercano y Accesible',                 val:  1513.12 },
          { label: 'Administración General (Coordinación)',        val:  1166.08 },
          { label: 'Coordinación General de la Gestión',          val:   348.88 },
          { label: 'Protocolo y Ceremonial',                       val:   162.56 },
        ]
      },
      { label: 'H.C.D.', val: 2736.68, nota: 'Q1×4',
        programas: [
          { label: 'Formación y Sanción de las Ordenanzas',       val:  2736.68 },
        ]
      },
      { label: 'Juzgado de Faltas', val: 819.68, nota: 'Q1×4',
        programas: [
          { label: 'Administración General (Juzgado Faltas)',      val:   819.68 },
        ]
      },
    ],

    personal: {
      total: null,
      permanente: null,
      mensualizado: null,
      gastoTotal: 46439.72,
      paritaria: null,
      porSecretaria: [],
      componentes: [
        { label: 'Personal permanente',              val: 17628.55 },
        { label: 'Personal temporario',              val: 23085.00 },
        { label: 'Servicios extraordinarios (HE)',   val:  4437.36 },
        { label: 'Asignaciones familiares',          val:  1288.87 },
      ],
    },
  },

  /* ─────────────── 2027 ─────────────── */
  /* Presupuesto aprobado (cuando exista) */
  2027: {
    status: 'pending',
    fuente: 'Pendiente — Presupuesto 2027 (a aprobar en el HCD)',
    ipc: null,
    resumen: null,
    recursos: null,
    gastos: null,
    secretarias: [],
    personal: { total: null, porSecretaria: [], componentes: [] },
  },

};

// Equivalencias de nombres de secretarías entre años
const SEC_EQUIV = {
  'Educación y Cultura':         'Capital Humano',
  'Secretaría de Deporte':       'Capital Humano',
  'Jefatura de Gabinete':        'Coordinación de Gabinete',
  'Jefatura de Gabinete (*)':    'Coordinación de Gabinete',
  'Des. Humano y Hábitat':       'Capital Humano',
  'Desarrollo Humano y Hábitat': 'Capital Humano',
  'Licencias de Conducir / Atención al Vecino': 'Atención al Vecino',
  'Atención al Vecino':          'Coordinación de Gabinete',
  'Des. Territorial y Movilidad':'Obras Públicas y Des. Urbano',
  'Control Municipal':            'Trabajo y Producción',
  'Finanzas y Eficiencia del Estado': 'Finanzas y Efic. del Estado',
};


// Equivalencias de programas entre años
// Permite hacer matching 2024↔2025↔2026 aunque cambien los nombres
const PROG_EQUIV = {

  // ── Pares 2024 → 2025 ──
  'Hospital Odontológico':                          'Fort. Hospital Odontológico',
  'Fort. Hospital Odontológico':                    'Fort. Complejo Hospitalario',
  'Fort. Hospital Oftalmológico':                   'Fort. Complejo Hospitalario',
  'SAE':                                            'Servicio Alimentario Escolar (SAE)',
  'MESA Bonaerense (social)':                       'MESA Bonaerense',
  'Higiene Urbana':                                 'Higiene Urbana y Control Microbasurales',
  'Actividades Centrales HCD':                      'Formación y Sanción de Ordenanzas (HCD)',
  'Licencias / Atención al Vecino':                 'Atención al Vecino',
  'Oficina de Faltas':                              'Juzgado de Faltas',
  'Recursos Humanos':                               'Recursos Humanos (Finanzas)',

  // ── Pares 2025 → 2026 (labels reales del RAFAM Q1 2026) ──
  // Ambiente
  'Higiene Urbana y Control Microbasurales':        'Higiene Urbana y Control de Microbasurales',
  'Mantenimiento Sistema Alumbrado':                'Administración General',
  'Fort. Espacios Públicos':                        'Administración General',
  'Mantenimiento e Infraestructura Urbana':         'Administración General',
  'Arbolado Público':                               'Administración General',
  'Centro Educativo Ambiental':                     'Administración General',
  'Mantenimiento Infr. Sistema Pluvial':            'Administración General',
  'Fort. Cementerio Municipal':                     'Fortalecimiento del Cementerio Municipal',

  // Capital Humano
  'Servicio Alimentario Escolar (SAE)':             'Servicio Alimentario Escolar (SAE)',
  'MESA Bonaerense':                                'MESA Bonaerense',
  'Primera Infancia y Jardines Municipales':        'Primera Infancia y Jardines de Infantes Municipales',
  'Fort. Infraestructura Educativa':                'Fortalecimiento de la Infraestructura Educativa Formal e Informal',
  'Emergencia Social y Seg. Alimentaria':           'Emergencia Social y Seguridad Alimentaria',
  'Promoción Cultural y Patrimonial':               'Promoción Cultural y Patrimonial',
  'Protección y Restitución Derechos NNA':          'Niñez, Adolescencia y Familia',
  'Deporte Educativo':                              'Desarrollo Deportivo y Apoyo a deportistas, clubes e instituciones deportivas',
  'Fort. y Apoyo Deportistas y Clubes':             'Desarrollo Deportivo y Apoyo a deportistas, clubes e instituciones deportivas',
  'Economía Social y Popular':                      'Emergencia Social y Seguridad Alimentaria',
  'Plan Regularización Dominial Altos Podestá':     'Hábitat, Vivienda y Regularización dominial',
  'Ligas Deportivas y Juegos Bonaerenses':          'Ligas Deportivas y Juegos Bonaerenses',
  'Fort. e Infr. Centros Deportivos':               'Desarrollo Deportivo y Apoyo a deportistas, clubes e instituciones deportivas',
  'Géneros, Diversidad y DDHH':                     'Niñez, Adolescencia y Familia',
  'Espacios Comunitarios Territoriales':            'Espacios Comunitarios Territoriales',
  'Programa Inclusión Personas c/ Discapacidad':    'Niñez, Adolescencia y Familia',
  'Deporte Inclusivo':                              'Deporte en el Espacio Público',
  'Fort. Escuelas Municipales':                     'Fortalecimiento de las Instituciones Educativas',
  'Programa de Hábitat Sustentable':                'Hábitat, Vivienda y Regularización dominial',
  'Programa Familias Solidarias':                   'Familias Solidarias',
  'Red Secundaria Cloacal Loma Hermosa OC70291':    'Red Secundaria Cloacal LOMA HERMOSA - OC70291',
  'Red Secundaria Cloacal Loma Hermosa OC70094':    'Red Secundaria Cloacal LOMA HERMOSA - OC70094',
  'Red de Agua Potable y Cloaca Bº Maldonado':      'Red de Agua Potable y Cloaca - B° MALDONADO',
  'Red Cloacal Pluvial Vial Churruca':              'Hábitat, Vivienda y Regularización dominial',

  // Obras Públicas
  'Obras Viales':                                   'Administración General',
  'Obras de Infraestructura':                       'Administración General',
  'Bacheo y Repavimentación':                       'Administración General',
  'Fondo Infraestructura Municipal (FIM)':          'Administración General',
  'Servicios Generales (Obras)':                    'Servicios Generales',
  'Plan Integral Movilidad (Obras)':                'Plan Integral de Movilidad e Integración Territorial',
  'Plan Integral Movilidad (Territorial)':          'Plan Integral de Movilidad e Integración Territorial',
  'Licencias de Conducir (Obras)':                  'Licencias de Conducir',
  'Licencias de Conducir (Gob.)':                   'Licencias de Conducir',
  'Desarrollo Urbano y Hábitat Sustentable':        'Desarrollo Urbano y Hábitat Sustentable',
  'Plan Urbano Estratégico':                        'Plan Urbano Estratégico',
  'Ord. Centralidades y Estacionamiento':           'Ordenamiento de Centralidades y Estacionamiento Medido',
  'Ord. Centralidades (Territorial)':               'Ordenamiento de Centralidades y Estacionamiento Medido',
  'Puesta en Valor Espacios Verdes':                'Administración General',
  'Casa Propia - Construir Futuro':                 'Casa Propia - Construir Futuro',

  // Salud
  'Fort. Hospital Odontológico':                    'Fort. Complejo Hospitalario',
  'Fort. Hospital Oftalmológico':                   'Fort. Complejo Hospitalario',
  'Fort. Compl. Hospitalario':                      'Fortalecimiento del Complejo Hospitalario',
  'Fort. Sistema Atención Primaria':                'Fortalecimiento del Sistema de Atención Primaria de la Salud',
  'Fort. Sistema Atención Médica (SAME)':           'Fortalecimiento del Sistema de Atención Médica de Emergencias (SAME)',
  'Determinantes Sociales de la Salud':             'Determinantes Sociales de la Salud',
  'Red Pública Salud AMBA':                         'Administración General',
  'Fort. Programas Sanitarios':                     'Administración General',
  'Epidemiología y Control de Vectores':            'Administración General',
  'Antropozoonosis':                                'Administración General',
  'Plan SUMAR':                                     'Programa SUMAR',
  'Programa Proteger - Min. Salud':                 'Administración General',

  // Seguridad
  'Centro Atención a las Víctimas':                 'Centro de Atención a las Víctimas',
  'Coordinación Sistema Seguridad Local':           'Planificación y Coordinación del Sistema de Seguridad Local',
  'Defensa Civil':                                  'Servicios de Seguridad y Emergencias',
  'Fort. Sistema Protección Ciudadana':             'Fortalecimiento del Sistema de Protección Ciudadana',
  'Fort. Sistema Video Vigilancia':                 'Fortalecimiento del Sistema de Video Vigilancia Urbano - Ojos en Alerta',
  'Fort. Sistema Seguridad Vial':                   'Fortalecimiento del Sistema de Seguridad Vial',

  // Finanzas
  'Coordinación Políticas Económicas':              'Administración General',
  'Coordinación Servicios Informáticos':            'Coordinación y Administración de la Modernización del Estado',
  'Recursos Humanos (Finanzas)':                    'Coordinación y Administración de Recursos Humanos',
  'Coordinación y Adm. de Ingresos':               'Coordinación y Administración de los Ingresos Públicos',
  'Coordinación y Adm. de Gastos':                 'Coordinación y Administración de las Finanzas',

  // Coordinación de Gabinete → Secretaría de Coordinación (2026)
  'Comunicación y Contenido':                       'Comunicación y Prensa',
  'Prensa y Comunicación':                          'Comunicación y Prensa',
  'Coordinación General de la Gestión':             'Coordinación General de la Gestión',
  'Gobierno Cercano y Accesible':                   'Gobierno Cercano y Accesible',
  'Gobierno Cercano y Accesible (At. Vecino)':      'Gobierno Cercano y Accesible',
  'Defensa al Consumidor (Coord.)':                 'Gobierno Cercano y Accesible',
  'Protocolo y Ceremonial':                         'Protocolo y Ceremonial',

  // Trabajo
  'Plan Anual Seguridad e Higiene':                 'Plan Anual de Seguridad, Higiene y Ordenamiento del espacio público',
  'Plan Integral Ordenamiento Esp. Público':        'Plan Anual de Seguridad, Higiene y Ordenamiento del espacio público',
  'Plan Anual Seg., Higiene y Ord. Esp. Púb.':     'Plan Anual de Seguridad, Higiene y Ordenamiento del espacio público',
  'Gestión Integral Habilitaciones':                'Fortalecimiento de Inversiones y Emprendedores',
  'Formación para el Trabajo y Teletrabajo':        'Formación para el Trabajo y Teletrabajo',
  'Desarrollo Centros Comerciales':                 'Desarrollo Comercial y Promoción Industrial',
  'Desarrollo Parque Industrial y PYMES':           'Desarrollo del Parque Industrial',
  'Microcréditos 3FEmprende':                       'Microcréditos 3F Emprende',
  'Distrito Innovación y Conocimiento':             'Distrito de la Innovación y el Conocimiento',

  // Sec. General
  'Comunicación y Prensa':                          'Comunicacion y prensa',
  'Legal y Técnica':                                'Legal y Técnica',
  'Asuntos Institucionales':                        'Asuntos Institucionales',
  'Asuntos Institucionales (Sec. Gral.)':           'Asuntos Institucionales',
  'Asuntos Institucionales (Gob.)':                 'Asuntos Institucionales',
  'Juventud':                                       'Juventud',
  'Juventud (Gob.)':                                'Juventud',
  'Coordinación y Adm. de Gastos (Sec. Gral.)':    'Coordinación y Administración de Gastos',

  // HCD
  'Formación y Sanción de Ordenanzas':              'Formación y Sanción de las Ordenanzas Municipales',
  'Formación y Sanción de Ordenanzas (HCD)':        'Formación y Sanción de las Ordenanzas Municipales',
  'HCD - Actividades Centrales':                    'Formación y Sanción de las Ordenanzas Municipales',

  // Deuda
  'Deuda Flotante':                                 'Deuda Flotante',
  'Deuda Consolidada':                              'Deuda Consolidada',
  'Amortización deuda interna (flotante 2025 + propia)': 'Deuda Flotante',

  // ── Inversos 2026 → 2025 ──
  'Higiene Urbana y Control de Microbasurales':     'Higiene Urbana y Control Microbasurales',
  'Primera Infancia y Jardines de Infantes Municipales': 'Primera Infancia y Jardines Municipales',
  'Fortalecimiento de la Infraestructura Educativa Formal e Informal': 'Fort. Infraestructura Educativa',
  'Emergencia Social y Seguridad Alimentaria':      'Emergencia Social y Seg. Alimentaria',
  'Niñez, Adolescencia y Familia':                  'Protección y Restitución Derechos NNA',
  'Hábitat, Vivienda y Regularización dominial':    'Plan Regularización Dominial Altos Podestá',
  'Desarrollo Deportivo y Apoyo a deportistas, clubes e instituciones deportivas': 'Fort. y Apoyo Deportistas y Clubes',
  'Deporte en el Espacio Público':                  'Deporte Inclusivo',
  'Fortalecimiento de las Instituciones Educativas':'Fort. Escuelas Municipales',
  'Fortalecimiento del Complejo Hospitalario':      'Fort. Hospital Odontológico',
  'Fortalecimiento del Sistema de Atención Primaria de la Salud': 'Fort. Sistema Atención Primaria',
  'Fortalecimiento del Sistema de Atención Médica de Emergencias (SAME)': 'Fort. Sistema Atención Médica (SAME)',
  'Fortalecimiento del Sistema de Protección Ciudadana': 'Fort. Sistema Protección Ciudadana',
  'Fortalecimiento del Sistema de Video Vigilancia Urbano - Ojos en Alerta': 'Fort. Sistema Video Vigilancia',
  'Fortalecimiento del Sistema de Seguridad Vial':  'Fort. Sistema Seguridad Vial',
  'Centro de Atención a las Víctimas':              'Centro Atención a las Víctimas',
  'Planificación y Coordinación del Sistema de Seguridad Local': 'Coordinación Sistema Seguridad Local',
  'Servicios de Seguridad y Emergencias':           'Defensa Civil',
  'Coordinación y Administración de Recursos Humanos': 'Recursos Humanos (Finanzas)',
  'Coordinación y Administración de los Ingresos Públicos': 'Coordinación y Adm. de Ingresos',
  'Coordinación y Administración de la Modernización del Estado': 'Coordinación Servicios Informáticos',
  'Coordinación y Administración de las Finanzas':  'Coordinación y Adm. de Gastos',
  'Plan Anual de Seguridad, Higiene y Ordenamiento del espacio público': 'Plan Anual Seguridad e Higiene',
  'Fortalecimiento de Inversiones y Emprendedores': 'Gestión Integral Habilitaciones',
  'Desarrollo Comercial y Promoción Industrial':    'Desarrollo Centros Comerciales',
  'Desarrollo del Parque Industrial':               'Desarrollo Parque Industrial y PYMES',
  'Microcréditos 3F Emprende':                      'Microcréditos 3FEmprende',
  'Distrito de la Innovación y el Conocimiento':    'Distrito Innovación y Conocimiento',
  'Formación y Sanción de las Ordenanzas Municipales': 'Formación y Sanción de Ordenanzas',
  'Comunicacion y prensa':                          'Prensa y Comunicación',
  'Ordenamiento de Centralidades y Estacionamiento Medido': 'Ord. Centralidades y Estacionamiento',
  'Plan Integral de Movilidad e Integración Territorial': 'Plan Integral Movilidad (Obras)',
  'Servicios Generales':                            'Servicios Generales (Obras)',
  'Fortalecimiento del Cementerio Municipal':       'Fort. Cementerio Municipal',
  'Red Secundaria Cloacal LOMA HERMOSA - OC70291':  'Red Secundaria Cloacal Loma Hermosa OC70291',
  'Red Secundaria Cloacal LOMA HERMOSA - OC70094':  'Red Secundaria Cloacal Loma Hermosa OC70094',
  'Red de Agua Potable y Cloaca - B° MALDONADO':    'Red de Agua Potable y Cloaca Bº Maldonado',
  'Familias Solidarias':                            'Programa Familias Solidarias',
  'Casa Propia - Construir Futuro':                 'Casa Propia - Construir Futuro',
  'Programa SUMAR':                                 'Plan SUMAR',
};
